# Generated by Django 5.2.12 on 2026-03-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codenerix_geodata", "0003_auto_20180118_1209"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="citygeonameen",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="citygeonamees",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="continent",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="continentgeonameen",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="continentgeonamees",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="countrygeonameen",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="countrygeonamees",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="provincegeonameen",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="provincegeonamees",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="regiongeonameen",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="regiongeonamees",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="timezone",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                )
            },
        ),
    ]
